### ISSUE TITLE
Keep URL parameters on redirect

### ISSUE THREAD

**Issue by tiagozip** [cmdwm/0tr.me#2]
Can the redirect leave URL parameters? E.g.:
```
https://0tr.me/0VX7QAS?myparam=hello&param2=blahblah ->
https://twitter.com/willmccrudden/status/1639125781380239360?myparam=hello&param2=blahblah
```

**Comment by cmdwm** [comment]
Hi, 
This is not the intended behavior due to crawlers being able to crawl the site and mess with any analytic params you've set. 

You can, however, shorten a long link with the URL parameters and they will be retained on the raw redirect. 

If you want to add this feature, please make a pull request.
